// userLogAction.enum.ts
export enum UserLogActionEnum {
    FORGOT_PASSWORD = "FORGOT_PASSWORD",
    RESET_PASSWORD = "RESET_PASSWORD",
    UPDATE_PROFILE = "UPDATE_PROFILE",
    UPDATE_AVATAR = "UPDATE_AVATAR",
    UPDATE_PASSWORD = "UPDATE_PASSWORD",
    DELETE_ACCOUNT = "DELETE_ACCOUNT",
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    REFRESH_TOKEN = "REFRESH_TOKEN",
    SETUP_2FA = "SETUP_2FA",
    ENABLE_2FA = "ENABLE_2FA",
    DISABLE_2FA = "DISABLE_2FA",
    DELETE_AVATAR = "DELETE_AVATAR",
}
