// userLogAction.enum.ts
export enum UserLogActionEnum {
    FORGOT_PASSWORD = "FORGOT_PASSWORD",
    RESET_PASSWORD = "RESET_PASSWORD",
    UPDATE_PROFILE = "UPDATE_PROFILE",
    UPDATE_AVATAR = "UPDATE_AVATAR",
    DELETE_ACCOUNT = "DELETE_ACCOUNT",
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    REFRESH_TOKEN = "REFRESH_TOKEN",
}
