-- CREATE TABLE links (
--     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY , -- 主鍵
--     code VARCHAR(16) UNIQUE NOT NULL , -- 短網址，自動建立唯一索引
--     long_url TEXT NOT NULL , -- 長網址
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now() , -- 創建時間
--     expire_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days'), -- 7天的到期時間
--     creator_ip INET , -- 創建者ip
--     is_active BOOLEAN NOT NULL DEFAULT TRUE , -- 短網址是否活躍
--     CHECK ( expire_at >= created_at )
-- );
--
-- CREATE TABLE link_logs (
--     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
--     link_id BIGINT NOT NULL REFERENCES links(id) ON DELETE CASCADE , -- 外鍵 引用自links_id
--     log_info JSONB NOT NULL , -- log資訊
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now() -- 建立時間戳
-- );
--
-- -- 建立索引
-- CREATE INDEX IF NOT EXISTS idx_links_expire_at ON links(expire_at);
-- CREATE INDEX IF NOT EXISTS idx_link_logs_link_id ON link_logs(link_id);
-- CREATE INDEX IF NOT EXISTS idx_link_logs_link_created_at ON link_logs(created_at);


-- ALTER TABLE links ALTER COLUMN code DROP NOT NULL;
-- CREATE UNIQUE INDEX IF NOT EXISTS links_code_uidx ON links(code) WHERE code IS NOT NULL;

-- ALTER TABLE links ADD COLUMN short_url TEXT;

-- ALTER TABLE links DROP COLUMN short_url

-- 2025/11/04 建立link_task
-- CREATE TYPE link_task_status AS ENUM ('pending', 'processing', 'done', 'failed');
-- --
-- CREATE TABLE link_task (
--     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY , -- 主鍵
--     link_id BIGINT NOT NULL REFERENCES links(id) ON DELETE CASCADE , -- 外鍵，引用自link_id
--     payload JSONB NOT NULL DEFAULT '{}'::jsonb, -- 封包，存code, long_url, expire_at等
--     status link_task_status NOT NULL DEFAULT 'pending', -- 任務狀態，預設是pending
--     attempts INTEGER NOT NULL DEFAULT 0, -- 重試次數
--     available_at TIMESTAMPTZ NOT NULL DEFAULT now(), -- 下次可以執行的時間
--     locked_at     TIMESTAMPTZ, -- worker 鎖定時間
--     locked_by     TEXT, -- 被哪個 worker 取用
--     processed_at TIMESTAMPTZ, -- 成功完成時間
--     last_error TEXT, -- 最近一次錯誤的原因
--     last_error_at TIMESTAMPTZ, -- 最近一次錯誤的時間
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now()  -- 創建時間
-- );
-- --
-- -- -- 建立索引
-- -- -- 複合式索引
-- CREATE INDEX IF NOT EXISTS idx_link_task_available ON link_task(status, available_at);
--
-- -- 限制同一個link_id在pending/processing期間，只能保留一筆
-- CREATE UNIQUE INDEX IF NOT EXISTS ux_link_task_dedup ON link_task(link_id) WHERE status IN ('pending','processing');
--
-- -- 限制payload帶的資料，且不能為空
-- ALTER TABLE link_task ADD CONSTRAINT chk_payload_has_keys CHECK (payload ? 'code' AND payload ? 'long_url' AND payload ? 'expire_at');

-- unique 唯一性，表示資料只有這一筆，例如使用者用abc email註冊，那其他使用這就不能用這個註冊。

--     2025/11/18
-- CREATE TABLE users (
--     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY , -- 主鍵
--     email TEXT UNIQUE NOT NULL , -- 作為帳號, 自動建立唯一索引
--     password_hash TEXT NOT NULL , -- 密碼，不能用明文
--     nickname TEXT NOT NULL , -- 使用者名稱
--     -- 第三方登入
--     provider TEXT DEFAULT 'local',
--     provider_id TEXT,
--     --
--     is_email_verified BOOLEAN NOT NULL DEFAULT FALSE , -- email是否通過驗證
--     email_verified_at TIMESTAMPTZ , -- email通過驗證的時間
--     avatar_key TEXT ,  -- 使用者頭像
--     is_active BOOLEAN NOT NULL DEFAULT TRUE , -- 帳號是否啟用
--     deleted_at TIMESTAMPTZ , -- 軟刪除
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now() , -- 創建時間
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT now() , -- 更新時間，如使用者名稱、頭像等
--     last_login_at TIMESTAMPTZ , -- 最後登入時間
--     last_password_reset_at TIMESTAMPTZ  -- 最後更新密碼的時間
-- );

-- CREATE TABLE refresh_token (
--     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY , -- 主鍵
--     user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE , -- 外鍵
--     refresh_token_hash TEXT UNIQUE NOT NULL , -- 加入索引
--     user_agent TEXT , -- 裝置來源的原始資料
--     ip_address INET ,  -- 裝置ip
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now() ,
--     expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days') , -- 7天過期時間
--     revoked_at TIMESTAMP , -- 強制過期時間
--     device_info TEXT , -- 裝置資料
--     last_used_at TIMESTAMPTZ , -- 最後登入的時間
--     CHECK ( expires_at >= created_at ) -- 過期時間必須大於創建時間
-- );
